services:
  db:
    container_name: ibrahim_holding_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-ibrahim_holding_db}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_LOCAL_PORT:-5432}:${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-ibrahim_holding_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: